### ISSUE TITLE
Enable multiple RC creation from a template (e.g. to allow for HA)

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kb8or#14]
At the moment, when a POD needs a specific node selector (to facilitate high availability data deployments), multiple RC's must be created on disc.

The following pattern would allow any resource controller named es-template to be used as a template to create three RC's called es-data-az-1, es-data-az-2, es-data-az-3 and with the variable ${ az } set appropriately as the template is added to the deployment.

Additionally, multiple resource controller entries could be specified:
- For multiple RC's defined within the same directory.
- For a static list of multiple RC's from the same template name (RcName is a static value).
- For a dynamic list of RC's using the optional EnumName and EnumValues (RcName is generated from the EnumValues).

``` yaml
Deploy:
  Path: ../kb8or_deploys/elasticsearch
  MultiRC:
    Name: es-template
    Items:
    - RcName: es-data
      VarData:
        replicas: 1
        EnumName: az
        EnumValues:
        - az-1
        - az-2
        - az-3
```
