### ISSUE TITLE
Add eventual replica number to a deploy (to support slow starting clusters)

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kb8or#18]
Example scenario:
When deploying elsaticsearch, a single master needs to be started first before then adding multiple standby masters...

Add a key EventualReplicas to a deployment e.g.:  

``` yaml
Deploy:
  path: ./elastic_search/
  EventualReplicas:
    Rc: se-master
    replicas: 3
```

Alternatively, maybe this could be dealt with using a patch file e.g.:

``` yaml

es_master_replicas: 3
Deploy:
  path: ./elastic_search/
  PostDeployPatch:
    ResourceName: rc-master
    PatchFile: ./replica/patch
```

Then patch file could embody any post deployment change e.g.:

``` yaml
spec:
  replicas: ${ es_master_replicas }
```
