### ISSUE TITLE
Allow auto creation of namespaces when possible

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kb8or#21]
At the moment, kb8or will deploy to namespaces based on kb8or environment name. It will fail on versions of kubernetes where namespaces need to be explicitly created.

Allow namespaces to be created automatically if they don't exist e.g. when deploying to nfidd-vagrant, pass kubectl this yaml:

``` yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nfidd-vagrant
```
