### ISSUE TITLE
Allow detection of resource changes for redeploy

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kb8or#23]
Possibly create a md5 of the source resource and store it in a metadata item (e.g. kb8ResourceMd5) when creating / updating items so that upgrades only happen when resources actually change...

It would assume that no changes have been made to the resource that were not done by kb8or but could speed up deployments with no changes...?

Thoughts?

``` yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: '{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"nfidd-dev","name":"es-master-v3","uid":"4859f7b5-7275-11e5-aab0-0676feffb509","apiVersion":"v1","resourceVersion":"4651582"}}'
  creationTimestamp: 2015-10-14T13:12:58Z
  generateName: es-master-v3-
  labels:
    component: elasticsearch
    kb8_deploy_id: v3
    role: master
  kb8ResourceMd5: 5936d2167939ff8fa9e7ce78b300bf9e
.
.
.
```
