### ISSUE TITLE
Add delete resource

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kb8or#24]
It is possible that a resource has been renamed from a previous deploy and any new deploy will have conflicting resources: e.g.:

```
Error (exit code:'1') running 'kubectl create -f -':
The Service "checking-https" is invalid:spec.ports[0].nodePort: invalid value '30803': provided port is already allocated
```

Provide a feature for deleting an old name for a resource e.g.:

``` yaml
Deploys:
  - Path: ./myapp/kb8or
    Delete: services/checking-proxy
```
