### ISSUE TITLE
Enable base64 encoding of variables

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kb8or#31]
Either add an option to base64 encode file includes OR add a Function to base64 encode any variable.
Should be able to generate secrets from a bunch of files...

Would require #37 E.g:

``` yaml
my_var:
  Fn::FileData: /root/.secrets/secret-data-1

base64_var:
  Fn::Base64EncVar: my_var
```

Then in a resource:

``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  data-1: ${ base64_var }
```
