### ISSUE TITLE
Generate context and use that over Kb8Server

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kb8or#41]
To manage multiple namespaces for multiple clusters it is simpler for kb8or to have the namespace, cluster and user specified in the environment file. The settings for cluster, user and namespace should be managed separately from kb8or.

The logic can be:
1. Preserve current behaviour if a kb8server is set (but mark as deprecated take out of docs).
2. If there is a Kb8Context setting, error if kb8Server is set.

Kb8Context should have the following settings:

``` yaml
Kb8Context:
  cluster: production_cluster
  user: prod_user
  namespace: prod_namespace
```

All three should be mandatory to prevent any potential confusion.
The Kb8Context setting should only be available in the environment "context".
