### ISSUE TITLE
Improve secrets schema

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/kb8or#85]
Change the schema for FileSecrets, I was thinking this could be an array of "secrets" (to create more than one secret per deploy) e.g. it could also add a wildcard option to the path and glob the results e.g.:

```
FileSecrets:
- name: frontend-secrets
  path: ../secrets/${env}/myapp_frontend_secrets/*.sec
- name: tls
  path: ../secrets/${env}/certs/*.pem
```
